CREATE TABLE CARD
(
    CARD_ID                INT PRIMARY KEY NOT NULL,
    CARD_KANJI             NCHAR(1)        NOT NULL,
    HEISIG_INDEX_5_EDITION INT,
    HEISIG_INDEX_6_EDITION INT,
    KEYWORD_5_EDITION      VARCHAR(20),
    KEYWORD_6_EDITION      VARCHAR(20),
    ON_READING             NVARCHAR(20),
    KUN_READING            NVARCHAR(20)
);

CREATE TABLE LESSON
(
    LESSON_ID  INT PRIMARY KEY NOT NULL,
    LAST_FRAME INT             NOT NULL REFERENCES CARD (CARD_ID)
);

CREATE TABLE PRIMITIVE
(
    PRIMITIVE_ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    NEXT_FRAME   INT REFERENCES CARD (CARD_ID)     NOT NULL,
    SVG_PATH     VARCHAR(2048)                     NOT NULL,
    KEYWORD      VARCHAR(20)
);

CREATE TABLE CARD_PRIMITIVE
(
    CARD_ID      INT NOT NULL REFERENCES CARD (CARD_ID),
    PRIMITIVE_ID INT NOT NULL REFERENCES PRIMITIVE (PRIMITIVE_ID),
    PRIMARY KEY (CARD_ID, PRIMITIVE_ID)
);

CREATE TABLE TAG
(
    TAG_ID          INT PRIMARY KEY NOT NULL,
    TAG_NAME        NVARCHAR(50)    NOT NULL,
    TAG_DESCRIPTION NVARCHAR(500)
);

CREATE TABLE NOTE
(
    NOTE_ID INT PRIMARY KEY NOT NULL,
    CARD_ID INT REFERENCES CARD (CARD_ID)
);

CREATE TABLE CARD_TAG
(
    CARD_ID INT NOT NULL REFERENCES CARD (CARD_ID),
    TAG_ID  INT NOT NULL REFERENCES TAG (TAG_ID),
    PRIMARY KEY (CARD_ID, TAG_ID)
);
