@startuml

class Main

abstract gui.ControllerManager
enum gui.Controllers

class gui.controller.EditorScene
class gui.controller.LoadScene
class gui.controller.KanjiBrowser
class gui.controller.KanjiEditor

class util.Scheduler

class util.Configuration <<Singleton>>
class util.Logger <<Singleton>>
class util.DatabaseConnection <<Singleton>>

Main --> util.Configuration
Main --> util.Logger

Main ..> gui.controller.LoadScene
Main ..> gui.controller.QuizScene
Main ..> gui.controller.KanjiBrowser
Main ..> gui.controller.KanjiEditor

gui.controller.QuizScene --> util.Scheduler
util.Scheduler --> util.DatabaseConnection

@enduml