@startuml

class Main

abstract gui.ControllerManager
enum gui.Controllers

class gui.controller.EditorScene
class gui.controller.LoadScene
class gui.controller.KanjiBrowser
class gui.controller.KanjiEditor

class util.Model <<Singleton>>
class util.Logger
class util.Scheduler
class util.DatabaseConnection

Main ..> gui.controller.LoadScene
Main ..> gui.controller.QuizScene
Main ..> gui.controller.KanjiBrowser
Main ..> gui.controller.KanjiEditor

util.Model --> util.DatabaseConnection
util.Model --> util.Logger
util.Model --> util.Scheduler

@enduml