@startuml

class Main {
    - model: util.Model
}

abstract gui.ControllerManager {
    - {static} SwitchView(): void
    - {static} applicationScene: Scene
    + {static} SetScene: void
}

enum gui.Controllers {
    LOAD,
    QUIZ,
    KANJI_BROWSER,
    KANJI_EDITOR
}

class gui.controller.EditorScene {

}

class gui.controller.LoadScene {

}

class gui.controller.QuizScene {

}

class gui.controller.KanjiBrowser {

}
class gui.controller.KanjiEditor {

}

class util.Model <<Singleton>> {
    - databaseConnection: util.DatabaseConnection
}

class util.Logger {

}

class util.Scheduler {

}

class util.DatabaseConnection {

}

@enduml