CREATE TABLE CARD(
    CARD_ID INT PRIMARY KEY NOT NULL,
    KANJI NCHAR(1) NOT NULL,
    HEISIG_INDEX INT,
    LAPSES INT
);

CREATE TABLE RADICAL(
    RADICAL_ID INT PRIMARY KEY NOT NULL,
    KANJI NCHAR(1) NOT NULL
);

CREATE TABLE CARD_RADICAL(
    CARD_ID PRIMARY KEY NOT NULL REFERENCES CARD(CARD_ID),
    RADICAL_ID PRIMARY KEY NOT NULL REFERENCES RADICAL(RADICAL_ID)
);

CREATE TABLE TAG(
    TAG_ID INT PRIMARY KEY NOT NULL,
    TAG_NAME NVARCHAR(50) NOT NULL,
    TAG_DESCRIPTION NVARCHAR(500)
);

CREATE TABLE NOTE(
    NOTE_ID INT PRIMARY KEY NOT NULL,
    CARD_ID INT REFERENCES CARD(CARD_ID)
);

CREATE TABLE CARD_TAG(
    CARD_ID PRIMARY KEY NOT NULL REFERENCES CARD(CARD_ID),
    TAG_ID PRIMARY KEY NOT NULL REFERENCES TAG(TAG_ID)
);

